// Change modes
export const SET_BOX_SHADOW_MODE = 'SET_BOX_SHADOW_MODE';
export const SET_BORDER_RADIUS_MODE = 'SET_BORDER_RADIUS_MODE';
export const SET_ROTATE_3D_MODE = 'SET_ROTATE_3D_MODE';

// Set Color
export const HANDLE_BOX_COLOR = 'HANDLE_BOX_COLOR';
export const RESET_BOX_COLOR = 'RESET_BOX_COLOR';

// Set Gradient
export const HANDLE_GRADIENT_DIRECTION = 'HANDLE_GRADIENT_DIRECTION';
export const HANDLE_GRADIENT_COLOR_1 = 'HANDLE_GRADIENT_COLOR_1';
export const HANDLE_GRADIENT_COLOR_2 = 'HANDLE_GRADIENT_COLOR_2';

// Box Shadow
export const HANDLE_X_POSITION_BOX_SHADOW = 'HANDLE_X_POSITION_BOX_SHADOW';
export const HANDLE_Y_POSITION_BOX_SHADOW = 'HANDLE_Y_POSITION_BOX_SHADOW';
export const HANDLE_BLUR_BOX_SHADOW = 'HANDLE_BLUR_BOX_SHADOW';
export const HANDLE_SPREAD_BOX_SHADOW = 'HANDLE_SPREAD_BOX_SHADOW';
export const HANDLE_OPACITY_BOX_SHADOW = 'HANDLE_OPACITY_BOX_SHADOW';
export const TOGGLE_INSET_BOX_SHADOW = 'TOGGLE_INSET_BOX_SHADOW';
export const HANDLE_RESET_BOX_SHADOW = 'HANDLE_RESET_BOX_SHADOW';

// Border Radius
export const HANDLE_PIXELS_BORDER_RADIUS = 'HANDLE_PIXELS_BORDER_RADIUS';
export const HANDLE_PERCENTS_BORDER_RADIUS = 'HANDLE_PERCENTS_BORDER_RADIUS';
export const HANDLE_RESET_BORDER_RADIUS = 'HANDLE_RESET_BORDER_RADIUS';

// Rotate 3D
export const HANDLE_X_ROTATE_3D = 'HANDLE_X_ROTATE_3D';
export const HANDLE_Y_ROTATE_3D = 'HANDLE_Y_ROTATE_3D';
export const HANDLE_Z_ROTATE_3D = 'HANDLE_Z_ROTATE_3D';
export const HANDLE_ANGLE_ROTATE_3D = 'HANDLE_ANGLE_ROTATE_3D';
export const HANDLE_RESET_ROTATE_3D = 'HANDLE_RESET_ROTATE_3D';
