// Signin/Signup
export const SIGN_IN_BEGIN = 'SIGN_IN_BEGIN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_UP_BEGIN = 'SIGN_UP_BEGIN';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const HANDLE_SU_USERNAME = 'HANDLE_SU_USERNAME';
export const HANDLE_SU_EMAIL = 'HANDLE_SU_EMAIL';
export const HANDLE_SU_PASSWORD = 'HANDLE_SU_PASSWORD';

export const HANDLE_SI_USERNAME = 'HANDLE_SI_USERNAME';
export const HANDLE_SI_EMAIL = 'HANDLE_SI_EMAIL';
export const HANDLE_SI_PASSWORD = 'HANDLE_SI_PASSWORD';

export const LOG_OUT = 'LOG_OUT';

// Change modes
export const SET_BOX_SHADOW_MODE = 'SET_BOX_SHADOW_MODE';
export const SET_BORDER_RADIUS_MODE = 'SET_BORDER_RADIUS_MODE';
export const SET_ROTATE_3D_MODE = 'SET_ROTATE_3D_MODE';

// Box Shadow
export const HANDLE_X_POSITION_BOX_SHADOW = 'HANDLE_X_POSITION_BOX_SHADOW';
export const HANDLE_Y_POSITION_BOX_SHADOW = 'HANDLE_Y_POSITION_BOX_SHADOW';
export const HANDLE_BLUR_BOX_SHADOW = 'HANDLE_BLUR_BOX_SHADOW';
export const HANDLE_SPREAD_BOX_SHADOW = 'HANDLE_SPREAD_BOX_SHADOW';
export const HANDLE_OPACITY_BOX_SHADOW = 'HANDLE_OPACITY_BOX_SHADOW';
export const TOGGLE_INSET_BOX_SHADOW = 'TOGGLE_INSET_BOX_SHADOW';
export const HANDLE_RESET_BOX_SHADOW = 'HANDLE_RESET_BOX_SHADOW';

// Border Radius
export const HANDLE_PIXELS_BORDER_RADIUS = 'HANDLE_PIXELS_BORDER_RADIUS';
export const HANDLE_PERCENTS_BORDER_RADIUS = 'HANDLE_PERCENTS_BORDER_RADIUS';
export const HANDLE_RESET_BORDER_RADIUS = 'HANDLE_RESET_BORDER_RADIUS';

// Rotate 3D
export const HANDLE_X_ROTATE_3D = 'HANDLE_X_ROTATE_3D';
export const HANDLE_Y_ROTATE_3D = 'HANDLE_Y_ROTATE_3D';
export const HANDLE_Z_ROTATE_3D = 'HANDLE_Z_ROTATE_3D';
export const HANDLE_ANGLE_ROTATE_3D = 'HANDLE_ANGLE_ROTATE_3D';
export const HANDLE_RESET_ROTATE_3D = 'HANDLE_RESET_ROTATE_3D';
